apiVersion: v1
kind: Service
metadata:
  name: aritra-argocd-demo-project-service
  namespace: argocd-demo
spec:
  type: LoadBalancer
  selector:
    app: aritra-argocd-demo-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
