name: Update ArgoCD Deployment

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:  

permissions:
  id-token: write
  contents: write
  pull-requests: write
  repository-projects: write
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  update-deployment:
    runs-on: development

    steps:
    - name: Check out repository
      uses: actions/checkout@v2      

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.eu-west-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        # Define variables
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 1234567890.dkr.ecr.eu-west-1.amazonaws.com
        IMAGE_REPO_NAME="aritra-argocd-demo-project"  # Update this with your ECR repo name
        IMAGE_TAG="${{ github.sha }}"
        ECR_REGISTRY="1234567890.dkr.ecr.eu-west-1.amazonaws.com"  # Update this with your ECR registry

        # Build the Docker image
        docker build -t aritra-argocd-demo-project .

        # Tag the Docker image
        docker tag aritra-argocd-demo-project:latest 1234567890.dkr.ecr.eu-west-1.amazonaws.com/aritra-argocd-demo-project:$IMAGE_TAG

        # Push the Docker image to ECR
        docker push 1234567890.dkr.ecr.eu-west-1.amazonaws.com/aritra-argocd-demo-project:$IMAGE_TAG

    - name: Update deployment.yaml
      working-directory: argocd-demo
      run: |
        # Define variables
        IMAGE_REPO_NAME="aritra-argocd-demo-project"  # Update this with your ECR repo name
        IMAGE_TAG="${{ github.sha }}"
        ECR_REGISTRY="1234567890.dkr.ecr.eu-west-1.amazonaws.com"  # Update this with your ECR registry

        # Update the image in the deployment.yaml file
        sed -i "s|image:.*$|image: $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG|" deployment.yaml

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit changes
      working-directory: argocd-demo
      run: |
        git add deployment.yaml
        git commit -m "Update deployment image to $ECR_REGISTRY/$IMAGE_REPO_NAME:${{ github.sha }}"
        git push origin ${{ env.BRANCH_NAME }}

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Pull Request
      run: |
        gh pr create --base main --head ${{ env.BRANCH_NAME }} --title "Update deployment image to latest" --body "This PR updates the deployment image to the latest version." --label "argocd" --label "deployment"